# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='required', max_length=200, upload_to='uploads/%Y/%m/%d', verbose_name='image')),
            ],
        ),
    ]
